plone/cookieplone-templates

project/{{ cookiecutter.__folder_name }}/Makefile, sub/project_settings/{{ cookiecutter.__folder_name }}/backend/Makefile
=> Makefile improvements

frontend_addon/{{ cookiecutter.__folder_name }}/packages/{{ cookiecutter.frontend_addon_name }}/tsconfig.json
Added paths configuration for the package in the tsconfig so typescript can find imports correctly, for example:
```typescript
import type { MyBlockProps } from '@redturtle/volto-blocks/components/blocks/MyBlock/schema';
````
=> Added package path in tsconfig.json

README.md
This clarifies that the templates should be used through Cookieplone, not directly by integrators.
=> Disambiguate About description

frontend_addon/{{ cookiecutter.__folder_name }}/Makefile, frontend_addon/{{ cookiecutter.__folder_name }}/packages/{{ cookiecutter.frontend_addon_name }}/.release-it.json, sub/frontend_project/{{ cookiecutter.__folder_name }}/_project_files/Makefile, sub/project_settings/{{ cookiecutter.__folder_name }}/frontend/Makefile
This resolves all the `workspace:*` entries in the add-on `package.json` before releasing.
=> Better release for addons - Use the `prerelease` script from core

backend_addon/hooks/pre_prompt.py, project/hooks/pre_prompt.py
=> Print results of sanity checks

frontend_addon/{{ cookiecutter.__folder_name }}/.github/workflows/unit.yml, frontend_addon/{{ cookiecutter.__folder_name }}/Makefile, sub/frontend_project/{{ cookiecutter.__folder_name }}/_project_files/Makefile, sub/project_settings/{{ cookiecutter.__folder_name }}/frontend/Makefile
=> Fix references to ci-test command

backend_addon/cookiecutter.json, backend_addon/{{ cookiecutter.__folder_name }}/constraints.txt, backend_addon/{{ cookiecutter.__folder_name }}/scripts/create_site.py, backend_addon/{{ cookiecutter.__folder_name }}/setup.py, sub/project_settings/{{ cookiecutter.__folder_name }}/backend/scripts/create_site.py
For Plone 6.1 we should specify a distribution when the site is created, or else it's missing some needed packages.
Fixes #99
=> Fix site creation script for Plone 6.1

backend_addon/{{ cookiecutter.__folder_name }}/Makefile, sub/project_settings/{{ cookiecutter.__folder_name }}/backend/Makefile
This addresses #91 
If merged, from now on we will have 2 different commands in the backend:
- `make clean`: this will remove the virtualenv and instance configuration
- `make remove-data`: this will remove the data stored in `instance/var`
=> change clean command not to delete data and add a reset-data command to remove data

sub/project_settings/{{ cookiecutter.__folder_name }}/frontend/Dockerfile
I have doubts if the install command does not have to be a plain `make install`.
=> Improve the copy of the deps from the project to the boilerplate

.github/workflows/frontend_addon.yml, .github/workflows/project.yml, project/{{ cookiecutter.__folder_name }}/devops/tasks/swarm/task_swarm.yml
We can't use cookiecutter variables here, because it's in _copy_without_render
=> Fix public_network variable in task_swarm.yml

backend_addon/{{ cookiecutter.__folder_name }}/Makefile
If a different virtualenv is active while running `make install`, then `uv` will detect it and install there instead of into `.venv`. (See https://docs.astral.sh/uv/pip/environments/#using-arbitrary-python-environments) Then other commands fail, such as in plone/cookieplone#38
To avoid this we can explicitly set the `VIRTUAL_ENV` environment variable. (See https://docs.astral.sh/uv/pip/environments/#using-arbitrary-python-environments)
I tested and this avoids the problem that happened in plone/cookieplone#38
=> Make sure uv installs into the right virtualenv

backend_addon/{{ cookiecutter.__folder_name }}/.mrbob.ini, backend_addon/{{ cookiecutter.__folder_name }}/Makefile, backend_addon/{{ cookiecutter.__folder_name }}/README.md, backend_addon/{{ cookiecutter.__folder_name }}/bobtemplate.cfg, backend_addon/{{ cookiecutter.__folder_name }}/src/packagename/configure.zcml, backend_addon/{{ cookiecutter.__folder_name }}/src/packagename/controlpanel/configure.zcml, backend_addon/{{ cookiecutter.__folder_name }}/src/packagename/indexers/configure.zcml, backend_addon/{{ cookiecutter.__folder_name }}/src/packagename/permissions.zcml, backend_addon/{{ cookiecutter.__folder_name }}/src/packagename/profiles/default/controlpanel.xml, backend_addon/{{ cookiecutter.__folder_name }}/src/packagename/profiles/default/registry/main.xml, backend_addon/{{ cookiecutter.__folder_name }}/src/packagename/profiles/default/rolemap.xml, backend_addon/{{ cookiecutter.__folder_name }}/src/packagename/upgrades/configure.zcml, backend_addon/{{ cookiecutter.__folder_name }}/src/packagename/vocabularies/configure.zcml, sub/project_settings/{{ cookiecutter.__folder_name }}/backend/Makefile
Adding these markers, one can use `plonecli` to add features to the backend addon.
This needs https://github.com/plone/bobtemplates.plone/pull/568 to correctly work. 
And also some documentation that I will be adding in the backend package's README file, because it needs to run `plonecli` with the custom configuration file provided here.
I think that plonecli/bobtemplates.plone is mature enough and saves a lot of time when adding features to backend, and it will be definelty useful in a project/add-on generator like this.
=> Add plonecli/bobtemplates.plone compatible markers and configuration

sub/project_settings/{{ cookiecutter.__folder_name }}/frontend/packages/{{ cookiecutter.frontend_addon_name }}/src/index.js
@ericof crap, I just realised that either git or cookiecutter does not preserve the trailing CR, so ESlint complains the first time.
=> Fix lint in project frontend add-on and change to use direct mutations

frontend_addon/{{ cookiecutter.__folder_name }}/pnpm-workspace.yaml, sub/project_settings/{{ cookiecutter.__folder_name }}/backend/Dockerfile, sub/project_settings/{{ cookiecutter.__folder_name }}/backend/Dockerfile.acceptance, sub/project_settings/{{ cookiecutter.__folder_name }}/frontend/Dockerfile
If we remove the src folder, the packages that we may have installed through sources in mx.ini will not be available.
=> do not remove the src folder when bulding the docker image

project/cookiecutter.json
see Ticket #129 and my last comment https://github.com/plone/cookieplone-templates/issues/129#issuecomment-2613955761
Purpose: Clarify that not the speaking name, but the qualified URL part is needed e
here to create the proper url path to the repo.
Further Todo:
Validate the input and warn to avoid whitespace
=> Update project cookiecutter.json precise organization prompt

project/README.md, project/cookiecutter.json, project/tests/conftest.py, project/{{ cookiecutter.__folder_name }}/devops/Makefile, project/{{ cookiecutter.__folder_name }}/devops/stacks/{{ cookiecutter.hostname }}.yml, project/{{ cookiecutter.__folder_name }}/docker-compose.yml
see #151
possible improvements:
- ZEO version ist hard-coded independent of Plone version
- we might want to build a ZEO container based on the `plone-zeo` container in order to install project code and allow for custom conflict resolution
- `devops/.env_gha` should be removed for ZEO and FileStorage. I'd postpone this until the `project_classic` branch is merged to avoid conflicts.
=> Configurable storage

backend_addon/{{ cookiecutter.__folder_name }}/pyproject.toml
Fixes #4130
Setuptools >= 75.8.1 produces a distribution name that can't be loaded by existing releases of Plone. (See also https://github.com/plone/plone.autoinclude/pull/30 which fixes that problem for future Plone releases.)
=> Pin the version of setuptools used for building the package

frontend_addon/{{ cookiecutter.__folder_name }}/.gitignore
This allows other core folders to exist in the project.
=> In frontend_addon, ignore the core folder only from the project root

frontend_addon/{{ cookiecutter.__folder_name }}/Makefile
In some CI environments, services running inside a container cannot be accessed via the ip `127.0.0.1`. Another host must be used. So we need to "inform" Volto and Cypress of the new Plone host that is running in a container. Volto's Cypress tests allow this with the `API_PATH` environment variable. But Cypress tests do not inherit the OS environment variables. We need to pass the `API_PATH` variable explicitly.
If there is no `API_PATH` environment variable, `http://127.0.0.1:55001/plone` is used.
Closes #177
=> Allows the use of the API_PATH environment variable in CI

news/208.bugfix, templates/add-ons/backend/{{ cookiecutter.__folder_name }}/pyproject.toml, templates/projects/monorepo/{{ cookiecutter.__folder_name }}/repository.toml, templates/sub/project_settings/cookiecutter.json, templates/sub/project_settings/{{ cookiecutter.__folder_name }}/backend/pyproject.toml
Fixes #208
ref: [Cookieplone issue #92](https://github.com/plone/cookieplone/issues/92)
=> Add horse-with-no-namespace as test dependency for packages

news/211.internal, templates/projects/monorepo/{{ cookiecutter.__folder_name }}/CHANGELOG.md
The link in the current CHANGELOG.md boilerplate pointing to the docs is broken.
I tried to find a current valid link as replacement and provided it as PR.
Please review and replace with a more appropriate link if needed.
broken link:
https://6.docs.plone.org/volto/developer-guidelines/contributing.html#create-a-pull-request
expected possible destination used as replacement:
https://6.docs.plone.org/contributing/index.html#contributing-change-log-label
Suggestion: 
Use a multi step canonical redirection for this link in the future including a revision/version 
e.g. Specific link -> generic link -> current link -> destination
The broken one is present in cookieplone generated projects with this current setup:
'__generator_signature': 'Generated using [Cookieplone …
=> Acsr patch – update broken link to changelog docs in two CHANGELOG.md files

news/161.bugfix, templates/add-ons/frontend/{{ cookiecutter.__folder_name }}/.npmrc
The generated package includes a `babel.config.js` file that requires the `babel-plugin-react-intl` and `babel-preset-razzle` dependencies. These dependencies are not declared in the package, so they are neither in the root node_modules folder nor in the package's own node_modules folder. When some IDEs run ESLint, they don't recognize that these packages are located in the `.pnpm` subfolder of the root node_modules, which causes a "package not found" error.
So we hoist these packages. This causes them to be placed at the root of the `node_modules` folder in the monorepo root. This way, IDEs’ ESLint can see the packages, and the error no longer occurs.
Closes https://github.com/plone/cookieplone-templates/issues/161
=> Fix Eslint in IDEs

news/245.bugfix, templates/add-ons/frontend/{{ cookiecutter.__folder_name }}/packages/{{ cookiecutter.frontend_addon_name }}/tsconfig.json, tests/templates/add-ons/frontend/test_frontend_tsconfig.py
Add `*.ts` and `*.tsx` in include of `tsconfig.json`.
For Sonar analysis to work, the package must have at least one file that matches the include in `tsconfig.json`.
This solves the problem when the package only uses JS.
Since `tsconfig.json` already uses `"noEmit": True`, we won't have any side effects with this, because `"noEmit": True` tells Type Script not to compile the files.
Closes #245
=> Fixes Sonar analysis in front end package

news/285.feature, templates/add-ons/backend/{{ cookiecutter.__folder_name }}/src/packagename/setuphandlers/__init__.py
-----
We did this previously in bobtemplates.plone: https://github.com/plone/bobtemplates.plone/blob/6.x/bobtemplates/plone/addon/src/%2Bpackage.namespace%2B/%2Bpackage.name%2B/setuphandlers.py.bob#L15-L17
=> feat: Hide the upgrades package from site-creation and quickinstaller
