- sub/frontend_project/{{ cookiecutter.__folder_name }}/_project_files/Makefile
Do you remember why are we updating the `Makefile` for the project image builder, to me it has no sense. Anyways, the custom builds are failing now because this is not up to date.
> Missing entries in Makefile for projects

- sub/project_settings/{{ cookiecutter.__folder_name }}/frontend/Dockerfile
This fixes the images build, since we moved it to the Makefile
> Add build:deps to frontend Dockerfile build

- backend_addon/{{ cookiecutter.__folder_name }}/tox.ini
> Fix package name in tox coverage command

- project/{{ cookiecutter.__folder_name }}/.editorconfig
- project/{{ cookiecutter.__folder_name }}/.gitignore
> Fixes to .editorconfig .gitignore

- project/{{ cookiecutter.__folder_name }}/devops/README.md
- project/{{ cookiecutter.__folder_name }}/devops/inventory/group_vars/all/packages.yml
- project/{{ cookiecutter.__folder_name }}/devops/tasks/base/task_docker.yml
- Explicitely install the `sudo` package
- Use ansible variables to decided if this is a Debian or Ubuntu server
- Document that one needs to install Debian or Ubuntu on the server
> Improvements to support Debian based servers

- project/{{ cookiecutter.__folder_name }}/.vscode/settings.json
> Add default VSCode settings for black and isort

- frontend_addon/{{ cookiecutter.__folder_name }}/.eslintrc.js
- frontend_addon/{{ cookiecutter.__folder_name }}/.storybook/main.js
> Update the boileplate for `eslintrc.js` and `.storyboook/main.js`

- project/tests/test_project_backend.py
- sub/project_settings/tests/test_cutter.py
- sub/project_settings/{{ cookiecutter.__folder_name }}/backend/Dockerfile
- sub/project_settings/{{ cookiecutter.__folder_name }}/backend/Dockerfile.acceptance
- sub/project_settings/{{ cookiecutter.__folder_name }}/backend/requirements-docker.txt
As explained in #87 maintaining 2 files with requirements makes everything harder.
> remove requirements-docker.txt

- frontend_addon/cookiecutter.json
> Generate frontend_addon_name from title

- backend_addon/{{ cookiecutter.__folder_name }}/tox.ini
changed tox.ini in the backend template to use plone_version with the chosen version
> fix constraints in tox.ini

- sub/project_settings/{{ cookiecutter.__folder_name }}/frontend/packages/{{ cookiecutter.frontend_addon_name }}/src/index.js
Fix regarding https://github.com/plone/cookieplone-templates/issues/134
> fix lint to be in sync with github action

- frontend_addon/{{ cookiecutter.__folder_name }}/cypress/tests/example.cy.js
It needs to wait for the content to finish loading before saving.
> Fix the example cypress test

- project/{{ cookiecutter.__folder_name }}/devops/stacks/{{ cookiecutter.hostname }}.yml
- project/{{ cookiecutter.__folder_name }}/docker-compose.yml
> fix #153 - ClassciUI Traefik Basic Auth masks Zope app root Basis Auth

- .github/workflows/main.yml
- .github/workflows/test-repository.yml
- cookiecutter.json
- hooks/pre_prompt.py
- news/193.feature
- pyproject.toml
- templates/add-ons/backend/hooks/pre_prompt.py
- templates/projects/monorepo/hooks/pre_prompt.py
- templates/sub/project_settings/hooks/pre_gen_project.py
- tests/conftest.py
- tests/cookieplone-templates/conftest.py
- tests/cookieplone-templates/test_required_variables.py
- tests/cookieplone-templates/test_templates.py
- tests/templates/sub/cache/conftest.py
- tests/templates/sub/cache/test_sub_cache_cutter.py
- tests/templates/sub/frontend_project/conftest.py
- tests/templates/sub/project_settings/conftest.py
- uv.lock
> Support having 'hidden' templates in cookiecutter.json

- templates/add-ons/backend/{{ cookiecutter.__folder_name }}/README.md
> Fix README create site command

- .github/workflows/readme-link-check.yml
- README.md
- news/210.documentation
- templates/add-ons/backend/README.md
- templates/add-ons/documentation_starter/README.md
- templates/add-ons/frontend/README.md
- templates/projects/monorepo/README.md
- templates/projects/monorepo/{{ cookiecutter.__folder_name }}/README.md
- templates/sub/cache/README.md
- templates/sub/frontend_project/README.md
- templates/sub/project_settings/README.md
- Fix broken links
- License badge was rendering as "Invalid" due to no absolute URL
- Replace CI badge, as individual workflows can't be checked with the new CI structure
- Minor grammar and formatting fixes
> Add `readme-link-check.yml` for all the `README.md`s

- news/217.bugfix
- templates/add-ons/frontend/cookiecutter.json
- templates/projects/monorepo/cookiecutter.json
Fixes https://github.com/plone/cookieplone/issues/98
> Use the user's choice for use_prerelease_versions when picking the default Volto version

- README.md
- news/222.documentation
h/t to @erral in https://github.com/plone/cookieplone-templates/pull/217#issuecomment-2808722652
> Add command for running a remote branch

- news/249.feature
- templates/add-ons/backend/hooks/post_gen_project.py
- templates/add-ons/backend/{{ cookiecutter.__folder_name }}/pyproject.toml
- templates/add-ons/backend/{{ cookiecutter.__folder_name }}/src/packagename/browser/configure.zcml
- templates/add-ons/backend/{{ cookiecutter.__folder_name }}/src/packagename/configure.zcml
- tests/templates/add-ons/backend/test_backend_cutter_no_headless.py
this reproduces the same defaults we had in bobtemplates.plone's addon template
> Add browser-module with jbot- and static-setup for classic

- news/254.bugfix
- templates/add-ons/backend/{{ cookiecutter.__folder_name }}/Makefile
- templates/sub/classic_project_settings/{{ cookiecutter.__folder_name }}/backend/Makefile
- templates/sub/project_settings/{{ cookiecutter.__folder_name }}/backend/Makefile
> Be explicit about the Python version when running uv venv

- news/262.feature
- templates/add-ons/backend/{{ cookiecutter.__folder_name }}/Makefile
- templates/add-ons/backend/{{ cookiecutter.__folder_name }}/pyproject.toml
This way backend addon can be released seamesly with zest.releaser
> feat: add version marker file for zest.releaser

- news/264.bugfix
- templates/add-ons/backend/{{ cookiecutter.__folder_name }}/Makefile
- templates/sub/classic_project_settings/{{ cookiecutter.__folder_name }}/backend/Makefile
- templates/sub/project_settings/{{ cookiecutter.__folder_name }}/backend/Makefile
Fixes https://github.com/plone/cookieplone-templates/issues/264
> Don't specify Python version in Makefile

- news/274.bugfix
- templates/add-ons/frontend/{{ cookiecutter.__folder_name }}/packages/{{ cookiecutter.frontend_addon_name }}/.release-it.json
- templates/projects/monorepo/hooks/post_gen_project.py
- tests/templates/add-ons/frontend/test_frontend_cutter.py
- tests/templates/projects/monorepo/test_project_frontend.py
> Frontend: Add plonePrePublish settings to .release-it.json

- news/288.bugfix
- templates/projects/classic/cookiecutter.json
- templates/projects/monorepo/cookiecutter.json
Fixes https://github.com/plone/cookieplone-templates/issues/288
> Use the correct language code for Swedish
